#!/bin/sh
out_ip=$(ip r g 8.8.8.8 | awk '{ for(i=1; i<NF; i++) { if($i == "src") {print $(i+1); exit} } }')
: ${bootstrap_host:=$out_ip}
cd /usr/share/nginx/html
for release_file in *.tar.gz
do
	echo "Creating torrent for ${release_file}"
	/usr/local/bin/create-torrent \
		-o ${release_file}.torrent \
		--createdBy "DC/OS P2P Downloader" \
		--private true \
		--announce "${tracker_scheme:-http}://${tracker_host:-$bootstrap_host}:${tracker_port:-6969}/announce" \
		--urlList "${download_scheme:-http}://${download_host:-$bootstrap_host}:${download_port:-80}/${release_file}" \
		${release_file}
done
mkdir -p /run/nginx \
	&& chown nginx:nginx /run/nginx \
	&& /usr/sbin/nginx
exec su - chihaya -c /bin/chihaya
